# Generated by Django 5.1.6 on 2025-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
            ],
        ),
    ]
