# Generated by Django 5.0.7 on 2025-03-04 13:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('manager_id', models.IntegerField()),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('food_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('food_item_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=20)),
                ('sell_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('food_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_item', models.CharField(max_length=50)),
                ('cost_price', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('purchased_date', models.DateField()),
                ('payment_status', models.CharField(max_length=10)),
            ],
        ),
    ]
